version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: todoapi-swift-app:v1 # Вказуємо наш зібраний образ (або Docker Compose збере його сам, якщо тут буде просто ім'я)
    container_name: todoapi_app_container
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=todouser
      - DATABASE_PASSWORD=todopassword
      - DATABASE_NAME=tododb
      - VAPOR_ENVIRONMENT=development # Для автоматичних міграцій
    depends_on:
      - db
    networks:
      - todo_network

  db:
    image: postgres:15-alpine
    container_name: todoapi_db_container
    environment:
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopassword
      POSTGRES_DB: tododb
    ports:
      - "5433:5432" # Мапимо на 5433 хоста, щоб не конфліктувати
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data
    networks:
      - todo_network
    restart: unless-stopped

volumes:
  postgres_data_volume:

networks:
  todo_network:
    driver: bridge
